# 服务启动端口
server:
  port: 8080

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml #xml配置文件位置
  type-aliases-package: com.github.springbootvue.entity #实体类位置