# 服务启动端口
server:
  port: 8085

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ribbon-consumer #我们可以指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问

## Mybatis
mybatis:
  mapper-locations: mapper/*.xml #xml配置文件位置
  type-aliases-package: com.github.springbootmybatis.entity #实体类位置

## eureka配置
eureka:
    client:
      serviceUrl:
         defaultZone: http://localhost:8083/eureka/ #service访问路径