server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.10.130 # redis服务器地址
    port: 6379 # redis端口
    database: 0 # redis数据库索引
    jedis:
        pool:
          max-active: 300 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1s # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 100 # 连接池中的最大空闲连接
          min-idle: 20 # 连接池中的最小空闲连接
    timeout: 60000s # 连接超时时间（毫秒）

## Mybatis
#mybatis:
#  mapper-locations: mapper/*.xml #xml配置文件位置
#  type-aliases-package: com.github.springbootmybatis.entity #实体类位置
